// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABsD5YJV206XQsKPVJUYIeUut_-uy_Ik4',
    appId: '1:761363814982:web:a05965bbc170c693d10847',
    messagingSenderId: '761363814982',
    projectId: 'financetrack-79432',
    authDomain: 'financetrack-79432.firebaseapp.com',
    storageBucket: 'financetrack-79432.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIeSKpVKJDB5wVoKWhJxYQVlsXdSQF9hI',
    appId: '1:761363814982:android:3042f225bb2bcf0ad10847',
    messagingSenderId: '761363814982',
    projectId: 'financetrack-79432',
    storageBucket: 'financetrack-79432.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxdDtWsxocT2de45_-vxOqafXjjNOAkY4',
    appId: '1:761363814982:ios:a68f0735761facbcd10847',
    messagingSenderId: '761363814982',
    projectId: 'financetrack-79432',
    storageBucket: 'financetrack-79432.firebasestorage.app',
    iosBundleId: 'com.example.taxMateV4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxdDtWsxocT2de45_-vxOqafXjjNOAkY4',
    appId: '1:761363814982:ios:a68f0735761facbcd10847',
    messagingSenderId: '761363814982',
    projectId: 'financetrack-79432',
    storageBucket: 'financetrack-79432.firebasestorage.app',
    iosBundleId: 'com.example.taxMateV4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABsD5YJV206XQsKPVJUYIeUut_-uy_Ik4',
    appId: '1:761363814982:web:005ebf82821cc02bd10847',
    messagingSenderId: '761363814982',
    projectId: 'financetrack-79432',
    authDomain: 'financetrack-79432.firebaseapp.com',
    storageBucket: 'financetrack-79432.firebasestorage.app',
  );

}